title = "NPT simulations for Hard Spheres"

[system]
particles = 216
density = 0.75
temperature = 1.0
pressure = 5.1

    [displacements]
    position = 0.13
    logvolume = 0.001

[simulation]
equilibration = 5000000
sampling = 7000000
